# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- starter

pool:
  vmImage: windows-latest

steps:
- task: MicrosoftSecurityDevOps@1
  inputs:
    Command: run
    policy: azuredevops
    publish: true

